1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$



In [4]:
import numpy as np
from numpy import linalg as LA
np.set_printoptions(precision=2, suppress=True)
matrix_a = np.array([[1, 2, 0],
              [0, 0, 5],
             [3, -4, 2],
             [1, 6, 5],
             [0, 1, 0]])
print(f'Матрица A:\n{matrix_a}')

matrix_u, s, W = np.linalg.svd(matrix_a)
matrix_v = W.T
matrix_d = np.zeros_like(matrix_a, dtype=float)
matrix_d[np.diag_indices(min(matrix_a.shape))] = s
print(f'Матрица D:\n{matrix_d}')
print(f'Матрица U:\n{matrix_u}')
print(f'Матрица V:\n{matrix_v}')

print(np.dot(np.dot(matrix_u, matrix_d), V.T))

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]



2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [5]:
# a) Евклидова норма:
matrix_d[0,0]

8.824868854820442

In [7]:
# б) норму Фробениуса.
np.sum(matrix_d ** 2) ** (1/2)

11.045361017187261