Практическое задание Методичка №1


Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.



а) Произведение не определено
<br>
б) Произведение определено, размерность 2х3
<br>
в) Произведение определено, размерность 8х8
<br>
г) Произведение определено, размерность 4х4

2. Найти сумму и произведение матриц 

$A=
 \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}
$ 

и 

$B= 
 \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}
$




In [3]:
import numpy as np

In [4]:
A = np.array([[1, 2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
A + B

array([[5, 1],
       [3, 5]])

In [5]:
A.dot(B)

array([[ 4,  9],
       [12, -3]])

3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц 

$A=
 \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}
$, 

$B=
 \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}
$, 

$C=
 \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}
 $

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

4. Дана матрица $A=
 \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}
$. 

Вычислить $AA^{T}$ и $A^{T}A$.

In [7]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_T = A.T
A.dot(A_T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [8]:
A_T.dot(A).shape

(2, 2)

5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

Методичка №2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

1. Вычислить определитель:

a)
$
\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}
$


б)
$
\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}
$
 
в)
$
\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}
$


Решение:

a)
$
 \begin{vmatrix}
sinx; -cosx\\ 
cosx;  sinx
\end{vmatrix}
$ = $sin^{2}x -(-cos^{2}x)$ = 1

In [12]:
# b)

import numpy as np

B = np.matrix('4, 2, 3; 0, 5, 1; 0, 0, 9')
np.linalg.det(B)

180.0

In [15]:
# в)

C = np.matrix('1, 2, 3; 4, 5, 6; 7, 8, 9')
np.linalg.det(C)

0.0

2. Определитель матрицы $A$ равен $4$. Найти:

а) $det(A^{2})$;

б) $det(A^{T})$;

в) $det(2A)$.

Решение:

а) $det(A^{2})$ = $det(A) \times det(A)$ = 16

б) $det(A^{T})$ = $det(A)$ = 4

в) $det(2A)$ = $2^{rank(A)} \times det(A)$ = $2^{rank(A)} \times 4$ = $2^{rank(A) + 2}$

3. Доказать, что матрица

 $
 \begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}
 $
 
вырожденная.

In [16]:
rank = np.linalg.matrix_rank
inv = np.linalg.inv

A = np.matrix('-2, 7, -3; 4, -14, 6; -3, 7, 13')
print(f'Ранг матрицы: {rank(A)}')
try:
    print(f'Обратная матрица: {inv(A)}')
except:
    print('Нет обратной матрицы')

Ранг матрицы: 2
Нет обратной матрицы


Ранг матрицы меньше числа ее строк, и у нее отсутствует обратная матрица => Матрица 

$
 $
 \begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}
 $
$

вырождена

4. Найти ранг матрицы:

а) $
 \begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}
$

б) $
 \begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}
.$

In [17]:
A = np.matrix('1, 2, 3; 1, 1, 1; 2, 3, 4')
rank(A)

2

In [18]:
B = np.matrix('0, 0, 2, 1; 0, 0, 2, 2; 0, 0, 4, 3; 2, 3, 5, 6')
rank(B)

3