
__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей


$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

 

In [1]:
import numpy as np

In [4]:
def eig(matrix_a):
    w, v = np.linalg.eig(matrix_a)
    print(f'Матрица:\n{matrix_a}')
    print(f'Собственные векторы:\n{v}')
    print(f'Собственные значения:\n{w}')

In [5]:
matrix_a = np.array([[-1, -6], [2, 6]])
eig(matrix_a)

Матрица:
[[-1 -6]
 [ 2  6]]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]
Собственные значения:
[2. 3.]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.




$-1\begin{pmatrix}
1 & 0\\ 
0 & 1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.$

  =>  Любой вектор будет собственным

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.


$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$
=> Данный вектор является собственным вектором линейного оператора

In [6]:
matrix_a = np.array([[1, 1], [-1, 3]])
eig(matrix_a)

Матрица:
[[ 1  1]
 [-1  3]]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]
Собственные значения:
[2.00000002 1.99999998]


**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}$ => Данный вектор  не является собственным вектором линейного оператора


In [7]:
matrix_a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
eig(matrix_a)

Матрица:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Собственные значения:
[ 3. -3.  3.]
